package ui;

//import com.sun.xml.internal.messaging.saaj.soap.ImageDataContentHandler;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;
import java.util.TimerTask;
import logic.*;
import utility.MoodMaker;
import utility.TxtReader;

/**
 * This class is the base for the games UI done with Java Swing.
 */
public class FirstUI extends javax.swing.JFrame {

    private Lab lab;
    private Pet pet;
    private TxtReader tx;
    private MoodMaker mm = new MoodMaker();
    private FileSaver fs = new FileSaver("saves/first.txt");

    /**
     * Creates new form FirstUI
     */
    public FirstUI() throws IOException {
        initComponents();
        
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                pet.hungerDecreasesByOne();
                pet.thirstDecreasesByOne();
                pet.funDecreasesByOne();
                pet.bladderDecreasesByOne();
                pet.sleepDecreasesByOne();
                try {
                    mm.recogniseMood(pet);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FirstUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTextAreaTraits.setText(pet.toString());
                
//                System.out.print("I would be called every 10 seconds");
            }
        }, 2000, 10000);

        tx = new TxtReader("story/fullstory.txt");
        jTextAreaStory.setText(tx.makeAStringOfRows());

        lab = new Lab("Sonja");
        pet = new Pet("Lenni");
        try {
            lab.addPet(pet);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FirstUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextAreaTraits.setText(pet.toString());

        jLabel2.setIcon(new javax.swing.ImageIcon(lab.getPet("Lenni").getPicturePath()));

        fs.writeToASaveFile("saves/first.txt", pet.contentToASave());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonFeed = new javax.swing.JButton();
        jButtonGiveWater = new javax.swing.JButton();
        jButtonPlayWith = new javax.swing.JButton();
        jButtonTakeOut = new javax.swing.JButton();
        jLabel1Menu = new javax.swing.JLabel();
        jComboBoxPets = new javax.swing.JComboBox<>();
        jLabelChooseAPet = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        sleepButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaStory = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTraits = new javax.swing.JTextArea();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silly Naked Furry Bellybutton Pets<3");
        setSize(new java.awt.Dimension(900, 700));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonFeed.setText("Feed");
        jButtonFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedActionPerformed(evt);
            }
        });

        jButtonGiveWater.setText("Give water");
        jButtonGiveWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiveWaterActionPerformed(evt);
            }
        });

        jButtonPlayWith.setText("Play With");
        jButtonPlayWith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayWithActionPerformed(evt);
            }
        });

        jButtonTakeOut.setText("Take out");
        jButtonTakeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeOutActionPerformed(evt);
            }
        });

        jLabel1Menu.setFont(new java.awt.Font("URW Bookman L", 1, 15)); // NOI18N
        jLabel1Menu.setText("MENU");

        jComboBoxPets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet 1", "Pet 2" }));
        jComboBoxPets.setToolTipText("Select pet");
        jComboBoxPets.setName("Choose pet:"); // NOI18N

        jLabelChooseAPet.setText("Choose a pet:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        sleepButton.setText("Sleep");
        sleepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGiveWater)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPlayWith, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelChooseAPet)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonTakeOut, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(sleepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChooseAPet)
                    .addComponent(jComboBoxPets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(sleepButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFeed)
                    .addComponent(jButtonGiveWater)
                    .addComponent(jButtonPlayWith)
                    .addComponent(jButtonTakeOut))
                .addGap(16, 16, 16))
        );

        jTextAreaStory.setBackground(new java.awt.Color(254, 254, 254));
        jTextAreaStory.setColumns(20);
        jTextAreaStory.setForeground(new java.awt.Color(1, 1, 1));
        jTextAreaStory.setRows(5);
        jTextAreaStory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextAreaStory.setDisabledTextColor(new java.awt.Color(9, 5, 1));
        jTextAreaStory.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaStory);

        jTextAreaTraits.setEditable(false);
        jTextAreaTraits.setBackground(new java.awt.Color(63, 58, 54));
        jTextAreaTraits.setColumns(20);
        jTextAreaTraits.setForeground(new java.awt.Color(253, 251, 251));
        jTextAreaTraits.setRows(5);
        jTextAreaTraits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaTraitsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaTraits);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayWithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayWithActionPerformed
        pet.haveFun();
        jTextAreaTraits.setText(pet.toString());
    }//GEN-LAST:event_jButtonPlayWithActionPerformed

    private void jButtonFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedActionPerformed
        pet.eat();
        jTextAreaTraits.setText(pet.toString());
    }//GEN-LAST:event_jButtonFeedActionPerformed

    private void jTextAreaTraitsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaTraitsKeyPressed

    }//GEN-LAST:event_jTextAreaTraitsKeyPressed

    private void jButtonGiveWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiveWaterActionPerformed
        pet.drink();
        jTextAreaTraits.setText(pet.toString());
    }//GEN-LAST:event_jButtonGiveWaterActionPerformed

    private void jButtonTakeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeOutActionPerformed
        lab.takePetOut(pet);
        jTextAreaTraits.setText(pet.toString());
    }//GEN-LAST:event_jButtonTakeOutActionPerformed

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(lab.getPet("Merry").getPicturePath())));
    }//GEN-LAST:event_jLabel2KeyPressed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            fs.createANewSaveFile("first", lab);
        } catch (IOException ex) {
            Logger.getLogger(FirstUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fs.writeToASaveFile("saves/first.txt", pet.contentToASave());
        } catch (IOException ex) {
            Logger.getLogger(FirstUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void sleepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepButtonActionPerformed
        lab.sleepPet(pet);
        jTextAreaTraits.setText(pet.toString());
    }//GEN-LAST:event_sleepButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FirstUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FirstUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButtonFeed;
    private javax.swing.JButton jButtonGiveWater;
    private javax.swing.JButton jButtonPlayWith;
    private javax.swing.JButton jButtonTakeOut;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBoxPets;
    private javax.swing.JLabel jLabel1Menu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChooseAPet;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaStory;
    private javax.swing.JTextArea jTextAreaTraits;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton sleepButton;
    // End of variables declaration//GEN-END:variables
}
